### ISSUE TITLE
Running multiple listener instances requires partitions assigned?

### ISSUE THREAD

**Issue by bemurphy** [klarna/phobos#27]
Hi, just experimenting with Phobos at the moment (thanks, it's cool!) and running into an issue. This possibly stems from not fully understanding Kafka, and not so much Phobos.

I setup a handler, and then in 2 separate shells start separate instances.  This results in "Listener crashed, waiting 0.86s (No partitions assigned!)" messages.

Any docs/examples as to how to deal with this? Or is this not the intended use? I'm not totally clear on the concurrency of the handlers, I believe I'm thinking in sidekiq terms where you set a thread concurrency so that a process running waiting on say, network io, doesn't block handling of other requests.

Thanks for your time!

**EDIT**: I'm thinking `max_concurrency` in the config might be part of this story.  I'm thinking though of instances where you might want to run multiple consumers of the same topic because of memory concerns per instance. I'm not sure if this works with an 'at least once' consumption setup though, if each listener would consume the entry (perhaps Phobos DB Checkpoint deals with it?), or because they are part of the same consumer group that is balanced out. Again, probably need to read up more on Kafka.

**Comment by tulios** [comment]
Hi @bemurphy, you can use the `Phobos::Executor` to start and stop your listeners easily. About the error, when you let kafka create the topic automatically it usually creates a topic with a single partition and the way you parallelize work in kafka is consuming different partitions concurrently. The error `No partitions assigned!` means that kafka couldn't assign a different partition to this listener.

You can take a look here https://github.com/klarna/phobos/blob/master/utils/create-topic.sh
on how to create a topic with more partitions.

**Comment by bemurphy** [comment]
@tulios great! Thanks so much for the pointer to the example in the shell script, that will be useful in experimenting with this some more. I'll close this issue for now as I suspect I can run with that from here.  Thank you again, I appreciate it.

**Comment by tulios** [comment]
👌
