### ISSUE TITLE
Add support for passing message keys to handler

### ISSUE THREAD

**Issue by sergeyevstifeev** [klarna/phobos#28]
Right now message key is not passed to the handler. It is possible that information important for the handler may be contained in message key.

**Comment by tulios** [comment]
@sergeyevstifeev the key is in the metadata argument:

```ruby
def consume(payload, metadata)
  puts metadata.key
end
```

https://github.com/klarna/phobos/blob/master/lib/phobos/listener.rb#L116

**Comment by sergeyevstifeev** [comment]
Indeed 👍
