### ISSUE TITLE
Integrated Avro decoding

### ISSUE THREAD

**Issue by sergeyevstifeev** [klarna/phobos#29]
Right now the responsibility of handling avro schemas and decoding is left to the handler. It would be nice to have an option to pass an already parsed message to the handler while performing all the mundane decoding tasks inside Phobos.

**Comment by martinsvalin** [comment]
Phobos doesn't decode JSON messages, leaving that to the handlers. I think it's reasonable to leave Avro decoding up to the handler as well. There seems to be an opportunity for a library for encoding/decoding Avro with a similar focus on convenience as Phobos has for producing/consuming Kafka messages, but the two concerns are mostly orthogonal.

wdyt?

**Comment by klippx** [comment]
Exactly -^

**Comment by tulios** [comment]
We could have something similar to https://github.com/klarna/phobos_db_checkpoint
A drop in replacement for `Phobos::Handler` with Avro capabilities.

**Comment by martinsvalin** [comment]
@tulios - What would it do that's only relevant in a Phobos context? I'm all for making it easier to produce and consume Avro messages. But let's imagine encoding/decoding Avro was as easy as `JSON payload`, is there still some rough edge in the interaction between Avro and Kafka that would make sense to smooth out in Phobos?

**Comment by tulios** [comment]
When using Avro you have to download the schemas to be able to decode the messages and upload your own schemas to the registry before you produce messages. I can see those tasks been automated. Also, when decoding the messages you have to provide the Schema to the decoder and this could also be handled in a nicer way. But like you said it's not much but there is room for improvements.

**Comment by tulios** [comment]
With a plugin, it will be much easier to start new projects since you wouldn't have to setup anything special for Avro, just a `gem install phobos_avro` and (now I'm guessing) `phobos_avro setup`.

**Comment by martinsvalin** [comment]
Yes, but making Avro more ergonomic in Ruby can be done in a library with no dependency on Phobos. It's useful outside of a Kafka context. A library for Avro with some conventions and helpful setup tasks would be excellent, I imagine. (At least coming from the exposure to the current Avro gems I've had this week.)

We'll try to keep this in mind in our current work with Avro, and we can discuss more when we have a more concrete proposal for a library API.

**Comment by tulios** [comment]
What are our conclusions on this subject?

**Comment by martinsvalin** [comment]
None in regards to a better Avro library. But I think this issue should be closed.
