### ISSUE TITLE
Max bytes per partition should default to 1MB

### ISSUE THREAD

**Issue by jasondoc3** [klarna/phobos#44]
From ruby-kafka on `max_bytes_per_partition`:

> The default is 1MB, but increasing this number may lead to better throughtput since you'll need to fetch less frequently. Setting it to a lower value is not recommended unless you have so many partitions that it's causing network and latency issues to transfer a fetch response from a broker to a client. Setting the number too high may result in instability, so be careful.

If max bytes per partition is less than the max message size allowed on kafka (default is 1MB), it's possible that consumers won't be able to fetch from a partition and stall. The current phobos default is 500kb. If a message is produced to kafka that is above 500kb, it won't be able to be read by the consumer unless this setting is explicitly increased.

**Comment by jasondoc3** [comment]
May have been addressed cleaner in `ruby-kafka` directly be a recent commit. https://github.com/zendesk/ruby-kafka/pull/472

**Comment by klippx** [comment]
I think this is reasonable. If you come across any other inconstencies please let us know, we should be consistent with ruby-kafka recommendations.
