### ISSUE TITLE
Allow Phobos to run in apps with ActiveSupport 3

### ISSUE THREAD

**Issue by mehdimu** [klarna/phobos#57]
Hi,

I am trying to install this gem into an existing application. The application is quite old, and uses `rails 3` with `ruby 2.3.4`. 

If there is a way to install this gem with `activesupport 3`? I am not able to upgrade the `activesupport` on my existing application, since it wouldn't work with `rails 3`.

Any ideas or tips? Perhaps can I monkey patch this gem to make it work with `activesupport 3`?

Please and Thank You!
Cheers,
Ali

**Comment by klippx** [comment]
I think it works with active support 3.0.0 actually. Maybe you can fork, edit the gemspec by setting

```
spec.add_dependency 'activesupport', '>= 3.0.0'
```

And then test your application using this forked version? If it works well, you can make a pull request to us.

None of my business, but what is your use case? Depending on what it is, maybe another idea is to create a separate app. I guess if you aim to produce messages the PR is quite valid 👍

**Comment by klippx** [comment]
Thank you for your contribution! ❤️
