### ISSUE TITLE
Silent fail in default configuration

### ISSUE THREAD

**Issue by imanel** [klarna/phobos#66]
After calling `phobos init` new configuration is generated, but when trying to run it it silently fails (no error, no processing).

The reason for that is that default yaml has [backoff configuration](https://github.com/klarna/phobos/blob/68807e5ad8f156acda3575bb37fc1f6274d3d1fa/config/phobos.yml.example#L114-L116) , which is passed [from listener](https://github.com/klarna/phobos/blob/68807e5ad8f156acda3575bb37fc1f6274d3d1fa/lib/phobos/listener.rb#L124) to base class, which fails with error "undefined method / for nil" in [this line](https://github.com/klarna/phobos/blob/68807e5ad8f156acda3575bb37fc1f6274d3d1fa/lib/phobos.rb#L54). Problem seems to be that YAML is treating default config keys as string and not as symbols, and while in other places it's converted correctly, here as nested hash it fails.

After removing those three lines it works again, but that's temporary hack and not a fix for actual problem.

Tested Ruby version: 2.4.2

**Comment by klippx** [comment]
Thanks for the analysis! Since you basically found and analyzed it, would you like to contribute with a fix? If you rather not, we will fix it, if so let us know what you prefer ⚖️

**Comment by imanel** [comment]
Please feel free to fix it - unfortunately I don't have too much time nowdays.
