### ISSUE TITLE
Best practices on high-availability

### ISSUE THREAD

**Issue by fxn** [klarna/phobos#70]
Hey, this is a question rather than an issue (asking here as per @klippx's suggestion).

I am working on a consumer that has to process messages from one topic, which has only one partition. That listener is critical, so I am thinking about having two machines up connected to Kafka (with the same group ID). As far as I understand, one of them will remain connected but idle, because Kafka will assign the partition to one consumer instance and stick with it as long as the communication is doing good.

In case of a new deployment, I guess that if we fire up a new service instance, and after that stop the previous one sending the supported OS signals, the broker is going to automatically send messages to the new ones, and the offsets are going to be correct.

Does that sound fine? Do you have any recommendations for that kind of setup?

I guess, also, that if the machine unexpectdly crashes, the other one will take over but it might be receiving a handful of already processed messages (assuming the 10s period for offset commits that Phobos does by default). Do you have experience/advice in handling this kind of inconsistencies?

**Comment by klippx** [comment]
A core thing about "high availability" is to have more than one partition, so this unfortunate setup seems flawed at its very essence, right? Our experience with high availability is in the order of millions of events on 30+ partitions consumed by 6 instances, each having 2 as max concurrency, so about 12 consumers each having 2-3 partitions...

That said, we have never used Kafka in this way, so we are not sure how kafka / phobos will behave when having more than one consumer for a mono-partition. (Or more consumers than there is topics either, for that matter)

If I were to guess, I think it would probably end up with the kafka broker kick the extra consumer out and ruby-kafka would treat this as an exception and raise. This would cause phobos to try connecting again, forever. In the end, I think it would lead to a lot of noise in the error log. 

So, given the constraints, while it wouldn't be correct to say it this is a GREAT setup, on the other hand I think it would _technically_ work: If your consumer dies, then the other one will suddenly be able to connect and start consuming, acting as a failover.

But, please simulate it before making a decision. You can do that using our docker-compose, provided in the repo there is a nice yml for this which spins up what you need. You can use the ruby-kafka apis to create the required partitions and to produce to them, while you observe how your consumers behave when trying to connect and get partitions assigned.

IDEALLY: If possible, increase the number of partitions on your topic to 20 or 30 and spin up a lot of more consumers. This is more close to our experience/setup in consuming from kafka. Then you don't have to bother with the simulations and you would _actually_ have high availability.

**Comment by fxn** [comment]
Thanks @klippx. What you say about partitions makes sense, I'll see if this setup can be revised (it is a given for me).

I saw last week the errors you anticipate when a second thread tried to connect, but I have not tested if the listener eventually reconnects if the first one disconnects. I'll try that and report it here for the archives. After that I think we could close the issue/question.

**Comment by fxn** [comment]
So I see something strange.

If the listener has `max_concurrency` set to 2, looks like at some point Kafka is rebalancing because this message appears in the log

> ERROR -- RubyKafka : Error sending heartbeat: Kafka::RebalanceInProgress

Also, to my surprise from some point on BOTH threads are processing messages. I have 100 messages they have a sequential number in the payload to observe the evolution of consumption, two threads, the testing consumer prints a trace and sleeps for 0.5 in `consume`. When thread #1 gets to the 60th, rebalancing happens, thread #2 starts processing messages from the beginning, and thread #1 continues where it was. In particular all messages are processed twice within the same consumer group.

The behaviour is similar if I lower `max_concurrenty` to 1 and start two Phobos processes. Eventually the second one starts receiving all messages.

Also, I have observed that the OS signals `QUIT` and friends do not stop the listeners.

The application I am running is absolutely trivial, a script loads a topic with 100 test messages, and Phobos is setup with a trivial consumer whose `consume` method prints and sleeps. It sleeps because 100 messages are consumed in no time and it is difficult to observe parallel conflicting consumers.

What do you think?

**Comment by fxn** [comment]
I have tried with the command-line tools distributed with Kafka, and they work fine with one partition. One listener is getting messages, and the rest just remain idle. If I kill the first listener, Kafka rebalances and one of the other ones in the same consumer group take over.

**Comment by fxn** [comment]
With a plain ruby-kafka consumer I get the same behavior. Closing then, I think I have enough to move on. Thanks!

**Comment by stAndrei** [comment]
`delivery: inline_batch` and `Phobos::BatchHandler` help me with
`Error sending heartbeat: Kafka::RebalanceInProgress`
