### ISSUE TITLE
Producer shutdown erases message buffer history

### ISSUE THREAD

**Issue by nbalsamo** [klarna/phobos#73]
According to the ruby-kafka documentation when a producer encounters a delivery failure after `deliver_messages` it will add the messages to a buffer and retry to send them the next time `deliver_messages` is called.  From the ruby-kafka documentation:

> #produce will buffer the message in the producer but will not actually send it to the Kafka cluster. Buffered messages are only delivered to the Kafka cluster once #deliver_messages is called. Since messages may be destined for different partitions, this could involve writing to more than one Kafka broker. Note that a failure to send all buffered messages after the configured number of retries will result in Kafka::DeliveryFailed being raised. This can be rescued and ignored; the messages will be kept in the buffer until the next attempt.

It seems when using `publish` and `publish_list` the producer is destroyed after its attempt to send, resulting in the loss of any buffered messages. Is this the expected experience?

The Phobos `async_publish_list` provides the desired buffered functionality, but it is suggested in the documentation to shutdown the producer if it is not within a handler. 

> Since the handler life cycle is managed by the Listener, it will make sure the producer is properly closed before it stops. When calling the producer outside a handler remember, you need to shutdown them manually before you close the application. Use the class method async_producer_shutdown to safely shutdown the producer.

We have an existing worker process publishing messages to a new Kafka cluster outside of a handler. For our system it is not acceptable to lose messages. What would be the down side to keeping a producer connected? At least until the buffer is emptied.

**Comment by klippx** [comment]
Sorry about the late reply. I am not entirely sure actually, I think it would be a good idea and very helpful to try to add a spec if possible or try to spin up some kafka/zk locally and try to manually test what is actually the case. 

I guess since a long time passed maybe you actually did that. If so, what was the result?

**Comment by klippx** [comment]
`publish_list` and `publish` both deliver all messages -synchronosly- before destroying the producer, so you should be good or you will know that it failed by capturing the exception.

**Comment by nbalsamo** [comment]
Thanks for getting back to this. We ended up using `async_publish_list`
