### ISSUE TITLE
Persistent offline producer cache?

### ISSUE THREAD

**Issue by rgaufman** [klarna/phobos#74]
This is more of a question than an issue. If the device is offline for an extended period of time, is there some strategy in phobos to store the messages locally until the connection is restored and they can be sent to the broker?

What about if the process is killed, is there any way to have a persistent store of these pending messages to be sent when the connection is restored?

**Comment by mensfeld** [comment]
Why would you post this around across various frameworks?

**Comment by klippx** [comment]
For **consuming** messages Phobos actually does support this if you use plugins https://github.com/klarna/phobos_db_checkpoint

The idea is that your consumer should fail the event (persisting it as a failure in the database) and then you can retry the event later.

You can also retry events from the console if you prefer, but there is actually a UI to inspect the events consumed and the see the number of failed events (and even retry/delete them from the UI): https://github.com/klarna/phobos_checkpoint_ui/

The problem with this is that events will not be consumed in the order they were received, so you need to live with that.

For **producing** messages however there is no such support. In theory something very similar could be done, but this would require changes to Phobos (adding `around_produce` or similar), abd then also changes to Phobos DB Checkpoint (something like `PhobosDbCheckpoint::ProducerHandler`). This handler could wrap producing storing failures for retrying later. Changes could be added to the DB Checkpoint API to retry producing messages.

Maybe this use case will show up for us in the future, but we dont have it right now. If you want to you would be more than welcome to contribute to Phobos 😋
